#.travis.yml

language: node_js
node_js:
  - "7.10"

branches:
  only:
    - master

before_script:
  - yarn global add @angular/cli
  - yarn global add angular-cli-ghpages

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@wittig.dk"


script:
  - ng build --prod --base-href "http://tech-flex.com/RSMuseum-ng/"

after_success:
  - ngh --no-silent

notifications:
  email:
    on_failure: change
    on_success: change
