#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - yarn global add @angular/cli
  - yarn global add angular-cli-ghpages

script:
  - ng build --prod --base-href "http://tech-flex.com/RSMuseum-ng/

after_success:
  - ngh

notifications:
  email:
    on_failure: change
    on_success: change
